### ISSUE TITLE
ISSUE: Door sensor entity hard-coded in lock_manager_common.txt

### ISSUE THREAD

**Issue by w0lf3h** [FutureTense/lock-manager#11]
Lines 340 and 356 of _lock_manager_common.txt_ have hard-coded entity_id listed for door sensors.

```
    - alias: CASE_LOCK_NAME Sensor Close
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
      trigger:
        entity_id: binary_sensor.zd2105us_5_recessed_door_window_sensor_access_control_door_window_open
        platform: state
        to: 'off'
      action:
        - service: script.LOCKNAME_conditional_notify
          data_template:
            boolean: input_boolean.LOCKNAME_dooraccess_notifications
            title: CASE_LOCK_NAME 
            message: "Closed"

    - alias: CASE_LOCK_NAME Sensor Opened
      condition:
        - condition: state
          entity_id: 'binary_sensor.allow_automation'
          state: 'on' 
      trigger:
        entity_id: binary_sensor.zd2105us_5_recessed_door_window_sensor_access_control_door_window_open
        platform: state
        to: 'on'
      action:
        - service: script.LOCKNAME_conditional_notify
          data_template:
            boolean: input_boolean.LOCKNAME_dooraccess_notifications
            title: CASE_LOCK_NAME    
            message: "Opened"
```
