### ISSUE TITLE
Unable to find service script/frontdoor_manual_notify

### ISSUE THREAD

**Issue by zhazell** [FutureTense/lock-manager#12]
Hello,

I've looked everywhere at the files and cannot find a service "manual_notify" being created. It seems in order to get any of the notifications, the automations and other services rely on this server. 

homeassistant.exceptions.ServiceNotFound: Unable to find service script/frontdoor_manual_notify

![image](https://user-images.githubusercontent.com/17417763/93822485-272d1480-fc15-11ea-832b-b4f133d46c4c.png)

Running HomeAssistant 0.115

**Comment by firstof9** [comment]
You create the script yourself :)

Here's an example:
```
frontdoor_manual_notify:
  mode: parallel
  sequence:
    - service: notify.phones
      data_template:
        title: "{{ title }}"
        message: "{{ message }}"
```
