### ISSUE TITLE
ISSUE: Entity not available/Yaml files not included?

### ISSUE THREAD

**Issue by Rojikku** [FutureTense/lock-manager#23]
**Describe the bug**
I'm a HASS noob, I admit, trying to figure things out. MOST of my stuff works, but I've never done any Lovelace stuff before. I got the UI set up appropriately, figured out that I had to install fold-entity-row (Which wasn't in the instructions), and got that far.
But the UI looks like so:
![lock-managerbroke](https://user-images.githubusercontent.com/1676068/95658996-59cb7e00-0aec-11eb-8345-f34d8a8d1b3b.png)

**Environment (please complete the following information):**
homeassistant docker using ozwdaemon over mqtt, all through docker.
Let me know if you actually need versions but I feel like this is a documentation issue.

**Logs**
Paste your error logs here.

**Additional context**
A bit of poking about in the packages/lock-manager/frontdoor section reveals the YAML for literally everything it says is missing, but this stuff isn't included in the configuration.yaml, so it doesn't load.
What am I supposed to do to get this to work? I'm sure the answer is like one line of code, but I'd rather just get an official answer and updated documentation than guess at it.

**Comment by firstof9** [comment]
Add the following to your `configuration.yaml` file:

```
homeassistant:
  packages: !include_dir_named packages
```

**Comment by Rojikku** [comment]
Good news:
Your suggestion worked perfectly. I would totally recommend that being in the docs though.

Bad news:
Even though the UI works perfectly, visually, it doesn't seem to actually interface with the lock. I set a code in the lock, hit Enable, it says Connected...And the door code won't open that door.

**Comment by firstof9** [comment]
Did you follow the [additional steps](https://github.com/FutureTense/lock-manager#additional-setup) outlined in the README?

**Comment by Rojikku** [comment]
Yeah. I can't promise I did it correctly, but I did try to. Does this look right?

automations.yaml (Whole):
```
- alias: homeassistant start-up
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.system_ready
    - service: input_boolean.turn_off
      entity_id: 'input_boolean.allow_automation_execution'

- alias: open_zwave_network_down
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.ozw_network_status
      to: "off"
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.allow_automation_execution

- alias: open_zwave_network_up
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: binary_sensor.ozw_network_status
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.ozw_network_status
      state: "on"
  action:
    - service: script.system_startup_cleanup
```
scripts.yaml (Whole)
```
# feel free to add post startup calls here
system_startup_cleanup:
  sequence:
    - condition: state
      entity_id: 'input_boolean.system_ready'
      state: 'off' 
    - service: homekit.start
    - service: input_boolean.turn_on
      entity_id: 'input_boolean.allow_automation_execution'
    - service: input_boolean.turn_on
      entity_id: input_boolean.system_ready
```

configuration.yaml (Clip)
```

# Mode
input_boolean:
  home:
    name: Home
    icon: mdi:home-account
  vacation:
    name: Vacation
    icon: mdi:home-outline
  sunrise:
    name: Sunrise
    initial: off
    icon: mdi:weather-sunset-up
  dusk:
    name: Dusk
    initial: off
    icon: mdi:weather-sunset-down
  night:
    name: Night
    initial: off
    icon: mdi:weather-night
  sleep:
    name: Sleep
    initial: off
    icon: mdi:sleep

  allow_automation_execution:
    name: 'Allow Automation'
    initial: off
  system_ready:
    name: 'System Ready'
    initial: off

binary_sensor:
  - platform: template
    sensors:
      allow_automation:
        friendly_name: "Allow Automation"
        value_template: "{{ is_state('input_boolean.allow_automation_execution', 'on') }}"

      system_ready:
        friendly_name: "System ready"
        value_template: "{{ is_state('input_boolean.system_ready', 'on') }}"
        device_class: moving  

```

**Comment by firstof9** [comment]
If you are running the openzwave beta you're almost there, but if you are just using the built in zwave stuff (I'm assuming you are since you just started using Home Assistant) you'll want to modify the automations slightly like this:
```
- alias: open_zwave_network_down
  initial_state: true
  trigger:
    platform: event
    event_type: zwave.network_stop
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.allow_automation_execution

- alias: open_zwave_network_up
  initial_state: true
  trigger:
    platform: event
    event_type: zwave.network_start
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.allow_automation_execution
```

**Comment by firstof9** [comment]
I swear I'll look into getting a Wiki setup for all this info too.

**Comment by Rojikku** [comment]
Nope! Good assumption, but I read a forum post about ozwdaemon supporting my garage door better, so I switched. So I'm on the beta.

**Comment by firstof9** [comment]
Alright so you need one last bit and you should be good:

```
binary_sensor:
  - platform: mqtt
    name: ozw_network_status
    state_topic: OpenZWave/1/status/
    value_template: >
      {{ "ON" if value_json.Status in ["driverAwakeNodesQueried", "driverAllNodesQueriedSomeDead", "driverAllNodesQueried"] else "OFF" }}
    json_attributes_topic: OpenZWave/1/status/
    device_class: "connectivity"
```

**Comment by Rojikku** [comment]
Does not work still.
https://kwiksetprodstorage.blob.core.windows.net/documents/kw_is_5066073_914[zw500].pdf
(Lock manual)
A code I setup on the lock works. I wanted to make a 6 digit code in the first slot that has the same first 4 digits, but it always unlocks after 4.
For testing purposes, I also added a second code of 1234 through the app, which doesn't work at all.
![Deadbolt](https://user-images.githubusercontent.com/1676068/95667462-8f945500-0b34-11eb-8f83-061440fc5099.png)
![Lock-Manager-Setup](https://user-images.githubusercontent.com/1676068/95667469-a33fbb80-0b34-11eb-9608-3a2b3336b890.png)

Any specific information you want?

**Comment by firstof9** [comment]
> A code I setup on the lock works. I wanted to make a 6 digit code in the first slot that has the same first 4 digits, but it always unlocks after 4.

Normal, you can't do this.

> For testing purposes, I also added a second code of 1234 through the app, which doesn't work at all.

What's the status of `input_boolean.allow_automation_execution`?

Also one last tweak I forgot:
```
- alias: open_zwave_network_up
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: binary_sensor.ozw_network_status
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.ozw_network_status
      state: "on"
  action:
    - service: script.system_startup_cleanup
```
to 
```
- alias: open_zwave_network_up
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.ozw_network_status
      to: "on"
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.allow_automation_execution
```

**Comment by Rojikku** [comment]
> > A code I setup on the lock works. I wanted to make a 6 digit code in the first slot that has the same first 4 digits, but it always unlocks after 4.
> 
> Normal, you can't do this.
> 
I can't get it to erase a code originally set on the lock? I thought it would overwrite the slot.

> 
> What's the status of `input_boolean.allow_automation_execution`?
> 
Off.
I'm restarting after that last tweak now.
Edit: The last tweak didn't turn it on. I could manually turn it on but I feel like that would defeat the purpose of the scripts.

Edit 2: The ozw_network_status is on, I manually looked after finally trying to figure out the yaml. However, the fact that it's on hasn't triggered allow_automation_execution.

Edit 3: Can confirm everything works as I expected (It overwrites the original 4 digit and 1234 works) once that boolean is turned on.

**Comment by firstof9** [comment]
>I can't get it to erase a code originally set on the lock? I thought it would overwrite the slot.

I misunderstood what you were attempting to do.

Alright I just double checked and this is exactly what I use for the automations

```
- alias: zwave down
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.ozw_network_status
      to: "off"
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.allow_automation_execution

- alias: Zwave_loaded_Start_System
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: binary_sensor.ozw_network_status
      to: "on"

  condition:
    - condition: state
      entity_id: binary_sensor.ozw_network_status
      state: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.allow_automation_execution
```

**Comment by Rojikku** [comment]
Noice! That actually works, I do believe. I restarted HASS and the execution is on this time.

**Comment by firstof9** [comment]
@FutureTense this solution might be best to update the README with as well.

**Comment by craigjwiener** [comment]
I had the same problem, but I'm not using open z-wave.   Its as if the interface does not trigger anything.  here are my files
Configuration.yaml

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automation.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

input_boolean: !include input_boolean.yaml

binary_sensor: !include binary_sensor.yaml


homeassistant:
  packages:  !include_dir_named packages

zwave:
 network_key: [redacted]
frontend:
  themes: !include_dir_merge_named themes

automation.yaml

- alias: homeassistant start-up
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.system_ready
    - service: input_boolean.turn_off
      entity_id: 'input_boolean.allow_automation_execution'

- alias: open_zwave_network_down
  initial_state: true
  trigger:
    platform: event
    event_type: zwave.network_stop
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.allow_automation_execution

- alias: open_zwave_network_up
  initial_state: true
  trigger:
    platform: event
    event_type: zwave.network_start
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.allow_automation_execution

binary_sensor.yaml

  - platform: template
    sensors:
      allow_automation:
        friendly_name: "Allow Automation"
        value_template: "{{ is_state('input_boolean.allow_automation_execution', 'on') }}"

      system_ready:
        friendly_name: "System ready"
        value_template: "{{ is_state('input_boolean.system_ready', 'on') }}"
        device_class: moving

input_boolean.yaml
allow_automation_execution:
  name: 'Allow Automation'
  initial: off

system_ready:
  name: 'System Ready'
  initial: off

scripts.yaml
# feel free to add post startup calls here
system_startup_cleanup:
  sequence:
    - condition: state
      entity_id: 'input_boolean.system_ready'
      state: 'off' 
    - service: homekit.start
    - service: input_boolean.turn_on
      entity_id: 'input_boolean.allow_automation_execution'
    - service: input_boolean.turn_on
      entity_id: input_boolean.system_ready
```
