### ISSUE TITLE
ISSUE: README update about notification script.

### ISSUE THREAD

**Issue by firstof9** [FutureTense/lock-manager#24]
**The Issue**
README needs a quip about creating their own notification script.

**Additional context**
An example that can be cited: 
```
frontdoor_manual_notify:
  mode: parallel
  sequence:
    - service: notify.phones
      data_template:
        title: "{{ title }}"
        message: "{{ message }}"
```
