### ISSUE TITLE
ISSUE: Code slots not updating

### ISSUE THREAD

**Issue by craigjwiener** [FutureTense/lock-manager#36]
**Describe the bug**
The interface is not setting the lock codes.   I uninstalled all zwave and installed OpenZwave MQTT etc.

**Environment (please complete the following information):**

- OS: HassOS 4.15
- Type of device: RPi4]
- Home Assistant version: .116.4
- Hassio/Docker/Core? 19.03.11
- Component version: [e.g. 0.1.2]

**Logs**
Update for sensor.front_door_code_slot_2 fails
4:25:41 PM – custom_components/lock-manager/sensor.py (ERROR) - message first occurred at 4:16:11 PM and shows up 40 times

**Screenshots**
![Screen Shot 2020-10-26 at 4 28 11 PM](https://user-images.githubusercontent.com/38117880/97239181-4127bd00-17a8-11eb-820a-504d7cab9373.png)

Automation.yaml

**Additional context**
Please add emails in plain/text format if possible and applicable.

**Comment by craigjwiener** [comment]
Automation Yaml

- alias: zwave down
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.ozw_network_status
      to: "off"
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.allow_automation_execution

- alias: Zwave_loaded_Start_System
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: binary_sensor.ozw_network_status
      to: "on"

  condition:
    - condition: state
      entity_id: binary_sensor.ozw_network_status
      state: "on"

  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.allow_automation_execution

binary_sensor
  - platform: mqtt
    name: ozw_network_status
    state_topic: OpenZWave/1/status/
    value_template: >
      {{ "ON" if value_json.Status in ["driverAwakeNodesQueried", "driverAllNodesQueriedSomeDead", "driverAllNodesQueried"] else "OFF" }}
    json_attributes_topic: OpenZWave/1/status/
    device_class: "connectivity"

Scripts:
# feel free to add post startup calls here
system_startup_cleanup:
  sequence:
    - condition: state
      entity_id: 'input_boolean.system_ready'
      state: 'off' 
    - service: homekit.start
    - service: input_boolean.turn_on
      entity_id: 'input_boolean.allow_automation_execution'
    - service: input_boolean.turn_on
      entity_id: input_boolean.system_ready

input_boolean.yaml
allow_automation_execution:
  name: 'Allow Automation'
  initial: off

system_ready:
  name: 'System Ready'
  initial: off

Config.yaml

homeassistant:
  packages: !include_dir_named packages
  
group: !include groups.yaml
automation: !include automation.yaml
script: !include script.yaml
scene: !include scenes.yaml

input_boolean: !include input_boolean.yaml

binary_sensor: !include binary_sensor.yaml

frontend:
  themes: !include_dir_merge_named themes

**Comment by firstof9** [comment]
https://github.com/FutureTense/lock-manager/wiki/Troubleshooting

**Comment by craigwiener** [comment]
Ok,  I followed everything for Open Z Wave.   They still don't communicate.  I can set the code/slot manually.   I also put everything in Visual Studio Code to make sure my spacing was correct.   Here is my config file.   Thank you for looking and helping.   As you can tell Im new to home assistant.  But learning a lot by setting up this.

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

input_boolean:
  allow_automation_execution:
    name: 'Allow Automation'
    initial: off

  system_ready:
    name: 'System Ready'
    initial: off

binary_sensor:
  - platform: template
    sensors:
      allow_automation:
        friendly_name: "Allow Automation"
        value_template: "{{ is_state('input_boolean.allow_automation_execution', 'on') }}"
  - platform: mqtt
    name: ozw_network_status
    state_topic: OpenZWave/1/status/
    value_template: >
      {{ "ON" if value_json.Status in ["driverAwakeNodesQueried", "driverAllNodesQueriedSomeDead", "driverAllNodesQueried"] else "OFF" }}
    json_attributes_topic: OpenZWave/1/status/
    device_class: "connectivity"
automation:
- alias: open_zwave_network_down
  initial_state: true
  trigger:
    - platform: state
      entity_id: binary_sensor.ozw_network_status
      to: "off"
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.allow_automation_execution

- alias: open_zwave_network_up
  initial_state: true
  trigger:
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: binary_sensor.ozw_network_status
      to: "on"
  condition:
    - condition: state
      entity_id: binary_sensor.ozw_network_status
      state: "on"
  action:
    - service: homeassistant.turn_on
      entity_id: input_boolean.allow_automation_execution

group: !include groups.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  packages: !include_dir_named packages
```

![Screen Shot 2020-10-27 at 1 23 48 PM](https://user-images.githubusercontent.com/71897615/97358193-20b73b80-1858-11eb-9cbd-61d928ce79e0.png)
